import Navbar from './navbar'
import Loginbar from './loginbar'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

export default function Layout({ children }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Yendo no, llegando</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Loginbar/>
          {children}
          <Navbar/>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://juanalmada.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Made with 🖤 
          </a>
        </footer>
      </div>
    </>
  )
}